/**
 * Curated list of well-known documentary titles for autocomplete.
 * The current week's puzzle title is always merged in at runtime so the answer is suggestable.
 */
export const DOCUMENTARY_TITLES: string[] = [
  '13th',
  '20 Feet from Stardom',
  '32 Sounds',
  'Abacus: Small Enough to Jail',
  'Abstract: The Art of Design',
  'After Tiller',
  'Amanda Knox',
  'American Factory',
  'American Movie',
  'American Pimp',
  'Amy',
  'An Inconvenient Sequel: Truth to Power',
  'An Inconvenient Truth',
  'Anvil! The Story of Anvil',
  'Apollo 11',
  'Armadillo',
  'Athlete A',
  'Banksy Does New York',
  'Bathtubs Over Broadway',
  'Becoming',
  'Beef',
  'Bending the Arc',
  'Best of Enemies',
  'Biggie & Tupac',
  'Bill Nye: Science Guy',
  'Blackfish',
  'Born into Brothels',
  'Bowling Alone',
  'Bowling for Columbine',
  'Bring Your Own Brigade',
  'Bros: After the Screaming Stops',
  'Buena Vista Social Club',
  'Capturing the Friedmans',
  'Cartel Land',
  'Catfish',
  'Chasing Coral',
  'Chasing Ice',
  'Citizenfour',
  'City of Gold',
  'Client 9: The Rise and Fall of Eliot Spitzer',
  'Comedian',
  'Cornelius',
  'Crazy Love',
  'Crip Camp',
  'Dark Days',
  'Dear Zachary',
  'Default',
  'Deliver Us from Evil',
  'Derrida',
  'Desert of Forbidden Art',
  'Dig!',
  'Doing Money',
  'Don\'t F**k with Cats',
  'Don\'t Look Back',
  'Drawing Restraint 9',
  'Drawing the Tiger',
  'Earthlings',
  'Earthrise',
  'Elvis Presley: The Searcher',
  'Evolution vs. God',
  'Exit Through the Gift Shop',
  'Faces Places',
  'Factory Girl',
  'Fahrenheit 11/9',
  'Fahrenheit 9/11',
  'Finding Vivian Maier',
  'Fire of Love',
  'Five Came Back',
  'Flow: For Love of Water',
  'Food, Inc.',
  'For Sama',
  'Forks Over Knives',
  'Free Solo',
  'Gaza',
  'Gimme Shelter',
  'Glen or Glenda',
  'God Loves Uganda',
  'Good Hair',
  'Grizzly Man',
  'Hacker',
  'Harlan County, U.S.A.',
  'Harry & Snowman',
  'Helvetica',
  'High Score',
  'Hoop Dreams',
  'Hot Coffee',
  'How to Survive a Plague',
  'Human',
  'I Am Chris Farley',
  'I Am Not Your Negro',
  'I Think We\'re Alone Now',
  'I, Tonya',
  'Icarus',
  'In Bruges',
  'In the Shadow of the Moon',
  'Indie Game: The Movie',
  'Inocente',
  'Into the Abyss',
  'Into the Inferno',
  'Iris',
  'It Might Get Loud',
  'Janis: Little Girl Blue',
  'Jim & Andy: The Great Beyond',
  'Jiro Dreams of Sushi',
  'Joan Rivers: A Piece of Work',
  'Joanna',
  'Jodorowsky\'s Dune',
  'Just Eat It: A Food Waste Story',
  'Kedi',
  'Keepers',
  'Keith Haring: Street Art Boy',
  'Keith Richards: Under the Influence',
  'Knock Down the House',
  'Kurt Cobain: Montage of Heck',
  'Land Without Bread',
  'Last Call at the Oasis',
  'Last Chance for Animals',
  'LFO: The Movie',
  'Life, Animated',
  'Listen to Me Marlon',
  'Little Dieter Needs to Fly',
  'Living on One Dollar',
  'Lo and Behold: Reveries of the Connected World',
  'Lost Angels',
  'Louisiana Story',
  'Making a Murderer',
  'Man on Wire',
  'Man Push Cart',
  'March of the Penguins',
  'Mavis!',
  'Maya Angelou: And Still I Rise',
  'McMillions',
  'Meet the Patels',
  'Metallica: Some Kind of Monster',
  'Minding the Gap',
  'Miss Americana',
  'Mr. Dynamite: The Rise of James Brown',
  'Murder on a Sunday Morning',
  'Muscle Shoals',
  'My Best Fiend',
  'My Kid Could Paint That',
  'My Octopus Teacher',
  'Nanook of the North',
  'Narrative of a... Never Mind the Bollocks',
  'National Geographic: Jane',
  'Nerdcore Rising',
  'Netflix: The Keepers',
  'No End in Sight',
  'Norman Lear: Just Another Version of You',
  'Notes on Blindness',
  'Nothing to Envy',
  'OJ: Made in America',
  'On the Ropes',
  'One Child Nation',
  'Operation Odessa',
  'Overnighters',
  'Pandemic: How to Prevent an Outbreak',
  'Paris Is Burning',
  'Patti Smith: Dream of Life',
  'Pause',
  'Period. End of Sentence.',
  'Pete Seeger: The Power of Song',
  'Petropolis: Aerial Perspectives on the Alberta Tar Sands',
  'Planet Earth',
  'Planet Earth II',
  'Prophecy',
  'Pumping Iron',
  'Qu\'est-ce qu\'on attend?',
  'Quiet Explosions: Healing the Brain',
  'Rapper\'s Delights',
  'Restrepo',
  'Return to Space',
  'Roadrunner: A Film About Anthony Bourdain',
  'Roger & Me',
  'Roman Polanski: Wanted and Desired',
  'Round Midnight',
  'Samsara',
  'Searching for Sugar Man',
  'Seaspiracy',
  'Shut Up & Sing',
  'Sicko',
  'Sin Nombre',
  'Sixteen Decisions',
  'Somm',
  'Spellbound',
  'Stories We Tell',
  'Street Fight',
  'Strictly Ballroom',
  'Strong Island',
  'Super Size Me',
  'Super Size Me 2: Holy Chicken!',
  'Surfwise',
  'Take Your Pills',
  'Talhotblond',
  'The Act of Killing',
  'The Alpinist',
  'The Aristocrats',
  'The B-52s: With the Wild Crowd!',
  'The Battered Bastards of Baseball',
  'The Biggest Little Farm',
  'The Border',
  'The Cave',
  'The Central Park Five',
  'The Champa Flower',
  'The Circus',
  'The Cleaners',
  'The Confession Tapes',
  'The Corporation',
  'The Cove',
  'The Creative Brain',
  'The Crime of the Century',
  'The Death of Superman Lives: What Happened?',
  'The Decline of Western Civilization',
  'The Defiant Ones',
  'The Diplomatic',
  'The Disaster Artist',
  'The Doc',
  'The Endless Summer',
  'The Eyes of Tammy Faye',
  'The First Monday in May',
  'The Flat',
  'The Fog of War',
  'The Four',
  'The Gatekeepers',
  'The Great Hack',
  'The Heroin Diaries',
  'The Human Element',
  'The Imposter',
  'The Inventor: Out for Blood in Silicon Valley',
  'The Invisible War',
  'The Jazz Loft According to W. Eugene Smith',
  'The Jinx',
  'The King of Kong',
  'The Lady Bird Johnson Special',
  'The Last Black Man in San Francisco',
  'The Last Dance',
  'The Last Waltz',
  'The Look of Silence',
  'The Lost City of Cecil B. DeMille',
  'The Minimalists',
  'The Nineties',
  'The Other Side of the Wind',
  'The Overnighters',
  'The Phantom',
  'The Pixar Story',
  'The Price of Everything',
  'The Rescue',
  'The Russian Five',
  'The September Issue',
  'The Sixties',
  'The Social Dilemma',
  'The Square',
  'The Thin Blue Line',
  'The Trials of Gabriel Fernandez',
  'The True Cost',
  'The Two Escobars',
  'The US and the Holocaust',
  'The Vietnam War',
  'The Waiting Room',
  'The War Room',
  'The White Helmets',
  'The Yes Men',
  'The Yes Men Fix the World',
  'They Shall Not Grow Old',
  'Three Identical Strangers',
  'Tiger King',
  'Tim\'s Vermeer',
  'Tina',
  'Tiny: A Story About Living Small',
  'Titanic: Blood and Steel',
  'Titticut Follies',
  'To Be and to Have',
  'To Hell and Back: The Kane Hodder Story',
  'Touching the Void',
  'Tower',
  'Trouble the Water',
  'Trust Me',
  'Truth and Illusion',
  'Truth or Consequences',
  'Tupac: Resurrection',
  'Undefeated',
  'Unfractured',
  'United States of Secrets',
  'Virunga',
  'Voices from the Grave',
  'Waltz with Bashir',
  'We Are Legion: The Story of the Hacktivists',
  'We Need to Talk About Kevin',
  'Welcome to Leith',
  'WeWork: Or the Making and Breaking of a $47 Billion Unicorn',
  'What Happened, Miss Simone?',
  'When We Were Kings',
  'Where to Invade Next',
  'White Right: Meeting the Enemy',
  'Who Is America?',
  'Who Killed the Electric Car?',
  'Wicked Game',
  'Wildcat',
  'Winged Migration',
  'Won\'t You Be My Neighbor?',
  'Woodstock',
  'Words on Bathroom Walls',
  'World War II in Colour',
  'Wrestling with Angels: Playwright Tony Kushner',
  'You\'ve Been Trumped',
  'Zero Days',
  'Zipper',
  'Zoom',
].sort((a, b) => a.localeCompare(b));